// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Request.proto

#ifndef PROTOBUF_proto_2fRequest_2eproto__INCLUDED
#define PROTOBUF_proto_2fRequest_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace Db {
namespace Proto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_proto_2fRequest_2eproto();
void protobuf_AssignDesc_proto_2fRequest_2eproto();
void protobuf_ShutdownFile_proto_2fRequest_2eproto();

class Update;
class Query;
class Rows;
class Fetch;
class FetchData;
class WriteAhead;

enum Fetch_Type {
  Fetch_Type_kNone = 0,
  Fetch_Type_kDocument = 1
};
bool Fetch_Type_IsValid(int value);
const Fetch_Type Fetch_Type_Type_MIN = Fetch_Type_kNone;
const Fetch_Type Fetch_Type_Type_MAX = Fetch_Type_kDocument;
const int Fetch_Type_Type_ARRAYSIZE = Fetch_Type_Type_MAX + 1;

enum WriteAhead_Type {
  WriteAhead_Type_kNone = 0,
  WriteAhead_Type_kTransact = 1,
  WriteAhead_Type_kUpdate = 2,
  WriteAhead_Type_kCommit = 3,
  WriteAhead_Type_kRollback = 4
};
bool WriteAhead_Type_IsValid(int value);
const WriteAhead_Type WriteAhead_Type_Type_MIN = WriteAhead_Type_kNone;
const WriteAhead_Type WriteAhead_Type_Type_MAX = WriteAhead_Type_kRollback;
const int WriteAhead_Type_Type_ARRAYSIZE = WriteAhead_Type_Type_MAX + 1;

enum Actions {
  kActNone = 0,
  kActInsert = 1,
  kActUpdate = 2
};
bool Actions_IsValid(int value);
const Actions Actions_MIN = kActNone;
const Actions Actions_MAX = kActUpdate;
const int Actions_ARRAYSIZE = Actions_MAX + 1;

// ===================================================================

class Update : public ::google::protobuf::MessageLite {
 public:
  Update();
  virtual ~Update();
  
  Update(const Update& from);
  
  inline Update& operator=(const Update& from) {
    CopyFrom(from);
    return *this;
  }
  
  static const Update& default_instance();
  
  void Swap(Update* other);
  
  // implements Message ----------------------------------------------
  
  Update* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const Update& from);
  void MergeFrom(const Update& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::std::string GetTypeName() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional .Db.Proto.Actions action = 1;
  inline bool has_action() const;
  inline void clear_action();
  static const int kActionFieldNumber = 1;
  inline Db::Proto::Actions action() const;
  inline void set_action(Db::Proto::Actions value);
  
  // optional int64 id = 2;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 2;
  inline ::google::protobuf::int64 id() const;
  inline void set_id(::google::protobuf::int64 value);
  
  // optional int32 storage_idx = 3;
  inline bool has_storage_idx() const;
  inline void clear_storage_idx();
  static const int kStorageIdxFieldNumber = 3;
  inline ::google::protobuf::int32 storage_idx() const;
  inline void set_storage_idx(::google::protobuf::int32 value);
  
  // optional string storage_name = 4;
  inline bool has_storage_name() const;
  inline void clear_storage_name();
  static const int kStorageNameFieldNumber = 4;
  inline const ::std::string& storage_name() const;
  inline void set_storage_name(const ::std::string& value);
  inline void set_storage_name(const char* value);
  inline void set_storage_name(const char* value, size_t size);
  inline ::std::string* mutable_storage_name();
  inline ::std::string* release_storage_name();
  
  // optional bytes buffer = 17;
  inline bool has_buffer() const;
  inline void clear_buffer();
  static const int kBufferFieldNumber = 17;
  inline const ::std::string& buffer() const;
  inline void set_buffer(const ::std::string& value);
  inline void set_buffer(const char* value);
  inline void set_buffer(const void* value, size_t size);
  inline ::std::string* mutable_buffer();
  inline ::std::string* release_buffer();
  
  // @@protoc_insertion_point(class_scope:Db.Proto.Update)
 private:
  inline void set_has_action();
  inline void clear_has_action();
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_storage_idx();
  inline void clear_has_storage_idx();
  inline void set_has_storage_name();
  inline void clear_has_storage_name();
  inline void set_has_buffer();
  inline void clear_has_buffer();
  
  ::google::protobuf::int64 id_;
  int action_;
  ::google::protobuf::int32 storage_idx_;
  ::std::string* storage_name_;
  ::std::string* buffer_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];
  
  friend void  protobuf_AddDesc_proto_2fRequest_2eproto();
  friend void protobuf_AssignDesc_proto_2fRequest_2eproto();
  friend void protobuf_ShutdownFile_proto_2fRequest_2eproto();
  
  void InitAsDefaultInstance();
  static Update* default_instance_;
};
// -------------------------------------------------------------------

class Query : public ::google::protobuf::MessageLite {
 public:
  Query();
  virtual ~Query();
  
  Query(const Query& from);
  
  inline Query& operator=(const Query& from) {
    CopyFrom(from);
    return *this;
  }
  
  static const Query& default_instance();
  
  void Swap(Query* other);
  
  // implements Message ----------------------------------------------
  
  Query* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const Query& from);
  void MergeFrom(const Query& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::std::string GetTypeName() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional string view_name = 2;
  inline bool has_view_name() const;
  inline void clear_view_name();
  static const int kViewNameFieldNumber = 2;
  inline const ::std::string& view_name() const;
  inline void set_view_name(const ::std::string& value);
  inline void set_view_name(const char* value);
  inline void set_view_name(const char* value, size_t size);
  inline ::std::string* mutable_view_name();
  inline ::std::string* release_view_name();
  
  // repeated bytes keys = 3;
  inline int keys_size() const;
  inline void clear_keys();
  static const int kKeysFieldNumber = 3;
  inline const ::std::string& keys(int index) const;
  inline ::std::string* mutable_keys(int index);
  inline void set_keys(int index, const ::std::string& value);
  inline void set_keys(int index, const char* value);
  inline void set_keys(int index, const void* value, size_t size);
  inline ::std::string* add_keys();
  inline void add_keys(const ::std::string& value);
  inline void add_keys(const char* value);
  inline void add_keys(const void* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& keys() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_keys();
  
  // optional bytes from_key = 4;
  inline bool has_from_key() const;
  inline void clear_from_key();
  static const int kFromKeyFieldNumber = 4;
  inline const ::std::string& from_key() const;
  inline void set_from_key(const ::std::string& value);
  inline void set_from_key(const char* value);
  inline void set_from_key(const void* value, size_t size);
  inline ::std::string* mutable_from_key();
  inline ::std::string* release_from_key();
  
  // optional bytes to_key = 5;
  inline bool has_to_key() const;
  inline void clear_to_key();
  static const int kToKeyFieldNumber = 5;
  inline const ::std::string& to_key() const;
  inline void set_to_key(const ::std::string& value);
  inline void set_to_key(const char* value);
  inline void set_to_key(const void* value, size_t size);
  inline ::std::string* mutable_to_key();
  inline ::std::string* release_to_key();
  
  // optional uint32 limit = 6;
  inline bool has_limit() const;
  inline void clear_limit();
  static const int kLimitFieldNumber = 6;
  inline ::google::protobuf::uint32 limit() const;
  inline void set_limit(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:Db.Proto.Query)
 private:
  inline void set_has_view_name();
  inline void clear_has_view_name();
  inline void set_has_from_key();
  inline void clear_has_from_key();
  inline void set_has_to_key();
  inline void clear_has_to_key();
  inline void set_has_limit();
  inline void clear_has_limit();
  
  ::std::string* view_name_;
  ::google::protobuf::RepeatedPtrField< ::std::string> keys_;
  ::std::string* from_key_;
  ::std::string* to_key_;
  ::google::protobuf::uint32 limit_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];
  
  friend void  protobuf_AddDesc_proto_2fRequest_2eproto();
  friend void protobuf_AssignDesc_proto_2fRequest_2eproto();
  friend void protobuf_ShutdownFile_proto_2fRequest_2eproto();
  
  void InitAsDefaultInstance();
  static Query* default_instance_;
};
// -------------------------------------------------------------------

class Rows : public ::google::protobuf::MessageLite {
 public:
  Rows();
  virtual ~Rows();
  
  Rows(const Rows& from);
  
  inline Rows& operator=(const Rows& from) {
    CopyFrom(from);
    return *this;
  }
  
  static const Rows& default_instance();
  
  void Swap(Rows* other);
  
  // implements Message ----------------------------------------------
  
  Rows* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const Rows& from);
  void MergeFrom(const Rows& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::std::string GetTypeName() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated bytes data = 1;
  inline int data_size() const;
  inline void clear_data();
  static const int kDataFieldNumber = 1;
  inline const ::std::string& data(int index) const;
  inline ::std::string* mutable_data(int index);
  inline void set_data(int index, const ::std::string& value);
  inline void set_data(int index, const char* value);
  inline void set_data(int index, const void* value, size_t size);
  inline ::std::string* add_data();
  inline void add_data(const ::std::string& value);
  inline void add_data(const char* value);
  inline void add_data(const void* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& data() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_data();
  
  // @@protoc_insertion_point(class_scope:Db.Proto.Rows)
 private:
  
  ::google::protobuf::RepeatedPtrField< ::std::string> data_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_proto_2fRequest_2eproto();
  friend void protobuf_AssignDesc_proto_2fRequest_2eproto();
  friend void protobuf_ShutdownFile_proto_2fRequest_2eproto();
  
  void InitAsDefaultInstance();
  static Rows* default_instance_;
};
// -------------------------------------------------------------------

class Fetch : public ::google::protobuf::MessageLite {
 public:
  Fetch();
  virtual ~Fetch();
  
  Fetch(const Fetch& from);
  
  inline Fetch& operator=(const Fetch& from) {
    CopyFrom(from);
    return *this;
  }
  
  static const Fetch& default_instance();
  
  void Swap(Fetch* other);
  
  // implements Message ----------------------------------------------
  
  Fetch* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const Fetch& from);
  void MergeFrom(const Fetch& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::std::string GetTypeName() const;
  
  // nested types ----------------------------------------------------
  
  typedef Fetch_Type Type;
  static const Type kNone = Fetch_Type_kNone;
  static const Type kDocument = Fetch_Type_kDocument;
  static inline bool Type_IsValid(int value) {
    return Fetch_Type_IsValid(value);
  }
  static const Type Type_MIN =
    Fetch_Type_Type_MIN;
  static const Type Type_MAX =
    Fetch_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    Fetch_Type_Type_ARRAYSIZE;
  
  // accessors -------------------------------------------------------
  
  // optional .Db.Proto.Fetch.Type type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::Db::Proto::Fetch_Type type() const;
  inline void set_type(::Db::Proto::Fetch_Type value);
  
  // optional int64 id = 2;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 2;
  inline ::google::protobuf::int64 id() const;
  inline void set_id(::google::protobuf::int64 value);
  
  // optional int32 storage_idx = 3;
  inline bool has_storage_idx() const;
  inline void clear_storage_idx();
  static const int kStorageIdxFieldNumber = 3;
  inline ::google::protobuf::int32 storage_idx() const;
  inline void set_storage_idx(::google::protobuf::int32 value);
  
  // optional string storage_name = 4;
  inline bool has_storage_name() const;
  inline void clear_storage_name();
  static const int kStorageNameFieldNumber = 4;
  inline const ::std::string& storage_name() const;
  inline void set_storage_name(const ::std::string& value);
  inline void set_storage_name(const char* value);
  inline void set_storage_name(const char* value, size_t size);
  inline ::std::string* mutable_storage_name();
  inline ::std::string* release_storage_name();
  
  // @@protoc_insertion_point(class_scope:Db.Proto.Fetch)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_storage_idx();
  inline void clear_has_storage_idx();
  inline void set_has_storage_name();
  inline void clear_has_storage_name();
  
  ::google::protobuf::int64 id_;
  int type_;
  ::google::protobuf::int32 storage_idx_;
  ::std::string* storage_name_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_proto_2fRequest_2eproto();
  friend void protobuf_AssignDesc_proto_2fRequest_2eproto();
  friend void protobuf_ShutdownFile_proto_2fRequest_2eproto();
  
  void InitAsDefaultInstance();
  static Fetch* default_instance_;
};
// -------------------------------------------------------------------

class FetchData : public ::google::protobuf::MessageLite {
 public:
  FetchData();
  virtual ~FetchData();
  
  FetchData(const FetchData& from);
  
  inline FetchData& operator=(const FetchData& from) {
    CopyFrom(from);
    return *this;
  }
  
  static const FetchData& default_instance();
  
  void Swap(FetchData* other);
  
  // implements Message ----------------------------------------------
  
  FetchData* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const FetchData& from);
  void MergeFrom(const FetchData& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::std::string GetTypeName() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int64 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int64 id() const;
  inline void set_id(::google::protobuf::int64 value);
  
  // optional bytes buffer = 2;
  inline bool has_buffer() const;
  inline void clear_buffer();
  static const int kBufferFieldNumber = 2;
  inline const ::std::string& buffer() const;
  inline void set_buffer(const ::std::string& value);
  inline void set_buffer(const char* value);
  inline void set_buffer(const void* value, size_t size);
  inline ::std::string* mutable_buffer();
  inline ::std::string* release_buffer();
  
  // @@protoc_insertion_point(class_scope:Db.Proto.FetchData)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_buffer();
  inline void clear_has_buffer();
  
  ::google::protobuf::int64 id_;
  ::std::string* buffer_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_proto_2fRequest_2eproto();
  friend void protobuf_AssignDesc_proto_2fRequest_2eproto();
  friend void protobuf_ShutdownFile_proto_2fRequest_2eproto();
  
  void InitAsDefaultInstance();
  static FetchData* default_instance_;
};
// -------------------------------------------------------------------

class WriteAhead : public ::google::protobuf::MessageLite {
 public:
  WriteAhead();
  virtual ~WriteAhead();
  
  WriteAhead(const WriteAhead& from);
  
  inline WriteAhead& operator=(const WriteAhead& from) {
    CopyFrom(from);
    return *this;
  }
  
  static const WriteAhead& default_instance();
  
  void Swap(WriteAhead* other);
  
  // implements Message ----------------------------------------------
  
  WriteAhead* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const WriteAhead& from);
  void MergeFrom(const WriteAhead& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::std::string GetTypeName() const;
  
  // nested types ----------------------------------------------------
  
  typedef WriteAhead_Type Type;
  static const Type kNone = WriteAhead_Type_kNone;
  static const Type kTransact = WriteAhead_Type_kTransact;
  static const Type kUpdate = WriteAhead_Type_kUpdate;
  static const Type kCommit = WriteAhead_Type_kCommit;
  static const Type kRollback = WriteAhead_Type_kRollback;
  static inline bool Type_IsValid(int value) {
    return WriteAhead_Type_IsValid(value);
  }
  static const Type Type_MIN =
    WriteAhead_Type_Type_MIN;
  static const Type Type_MAX =
    WriteAhead_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    WriteAhead_Type_Type_ARRAYSIZE;
  
  // accessors -------------------------------------------------------
  
  // optional .Db.Proto.WriteAhead.Type type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::Db::Proto::WriteAhead_Type type() const;
  inline void set_type(::Db::Proto::WriteAhead_Type value);
  
  // optional int64 sequence = 2;
  inline bool has_sequence() const;
  inline void clear_sequence();
  static const int kSequenceFieldNumber = 2;
  inline ::google::protobuf::int64 sequence() const;
  inline void set_sequence(::google::protobuf::int64 value);
  
  // optional int64 transact_id = 3;
  inline bool has_transact_id() const;
  inline void clear_transact_id();
  static const int kTransactIdFieldNumber = 3;
  inline ::google::protobuf::int64 transact_id() const;
  inline void set_transact_id(::google::protobuf::int64 value);
  
  // optional .Db.Proto.Update update = 4;
  inline bool has_update() const;
  inline void clear_update();
  static const int kUpdateFieldNumber = 4;
  inline const ::Db::Proto::Update& update() const;
  inline ::Db::Proto::Update* mutable_update();
  inline ::Db::Proto::Update* release_update();
  
  // @@protoc_insertion_point(class_scope:Db.Proto.WriteAhead)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_sequence();
  inline void clear_has_sequence();
  inline void set_has_transact_id();
  inline void clear_has_transact_id();
  inline void set_has_update();
  inline void clear_has_update();
  
  ::google::protobuf::int64 sequence_;
  ::google::protobuf::int64 transact_id_;
  ::Db::Proto::Update* update_;
  int type_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_proto_2fRequest_2eproto();
  friend void protobuf_AssignDesc_proto_2fRequest_2eproto();
  friend void protobuf_ShutdownFile_proto_2fRequest_2eproto();
  
  void InitAsDefaultInstance();
  static WriteAhead* default_instance_;
};
// ===================================================================


// ===================================================================

// Update

// optional .Db.Proto.Actions action = 1;
inline bool Update::has_action() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Update::set_has_action() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Update::clear_has_action() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Update::clear_action() {
  action_ = 0;
  clear_has_action();
}
inline Db::Proto::Actions Update::action() const {
  return static_cast< Db::Proto::Actions >(action_);
}
inline void Update::set_action(Db::Proto::Actions value) {
  GOOGLE_DCHECK(Db::Proto::Actions_IsValid(value));
  set_has_action();
  action_ = value;
}

// optional int64 id = 2;
inline bool Update::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Update::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Update::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Update::clear_id() {
  id_ = GOOGLE_LONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::int64 Update::id() const {
  return id_;
}
inline void Update::set_id(::google::protobuf::int64 value) {
  set_has_id();
  id_ = value;
}

// optional int32 storage_idx = 3;
inline bool Update::has_storage_idx() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Update::set_has_storage_idx() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Update::clear_has_storage_idx() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Update::clear_storage_idx() {
  storage_idx_ = 0;
  clear_has_storage_idx();
}
inline ::google::protobuf::int32 Update::storage_idx() const {
  return storage_idx_;
}
inline void Update::set_storage_idx(::google::protobuf::int32 value) {
  set_has_storage_idx();
  storage_idx_ = value;
}

// optional string storage_name = 4;
inline bool Update::has_storage_name() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Update::set_has_storage_name() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Update::clear_has_storage_name() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Update::clear_storage_name() {
  if (storage_name_ != &::google::protobuf::internal::kEmptyString) {
    storage_name_->clear();
  }
  clear_has_storage_name();
}
inline const ::std::string& Update::storage_name() const {
  return *storage_name_;
}
inline void Update::set_storage_name(const ::std::string& value) {
  set_has_storage_name();
  if (storage_name_ == &::google::protobuf::internal::kEmptyString) {
    storage_name_ = new ::std::string;
  }
  storage_name_->assign(value);
}
inline void Update::set_storage_name(const char* value) {
  set_has_storage_name();
  if (storage_name_ == &::google::protobuf::internal::kEmptyString) {
    storage_name_ = new ::std::string;
  }
  storage_name_->assign(value);
}
inline void Update::set_storage_name(const char* value, size_t size) {
  set_has_storage_name();
  if (storage_name_ == &::google::protobuf::internal::kEmptyString) {
    storage_name_ = new ::std::string;
  }
  storage_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Update::mutable_storage_name() {
  set_has_storage_name();
  if (storage_name_ == &::google::protobuf::internal::kEmptyString) {
    storage_name_ = new ::std::string;
  }
  return storage_name_;
}
inline ::std::string* Update::release_storage_name() {
  clear_has_storage_name();
  if (storage_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = storage_name_;
    storage_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional bytes buffer = 17;
inline bool Update::has_buffer() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Update::set_has_buffer() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Update::clear_has_buffer() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Update::clear_buffer() {
  if (buffer_ != &::google::protobuf::internal::kEmptyString) {
    buffer_->clear();
  }
  clear_has_buffer();
}
inline const ::std::string& Update::buffer() const {
  return *buffer_;
}
inline void Update::set_buffer(const ::std::string& value) {
  set_has_buffer();
  if (buffer_ == &::google::protobuf::internal::kEmptyString) {
    buffer_ = new ::std::string;
  }
  buffer_->assign(value);
}
inline void Update::set_buffer(const char* value) {
  set_has_buffer();
  if (buffer_ == &::google::protobuf::internal::kEmptyString) {
    buffer_ = new ::std::string;
  }
  buffer_->assign(value);
}
inline void Update::set_buffer(const void* value, size_t size) {
  set_has_buffer();
  if (buffer_ == &::google::protobuf::internal::kEmptyString) {
    buffer_ = new ::std::string;
  }
  buffer_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Update::mutable_buffer() {
  set_has_buffer();
  if (buffer_ == &::google::protobuf::internal::kEmptyString) {
    buffer_ = new ::std::string;
  }
  return buffer_;
}
inline ::std::string* Update::release_buffer() {
  clear_has_buffer();
  if (buffer_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = buffer_;
    buffer_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// -------------------------------------------------------------------

// Query

// optional string view_name = 2;
inline bool Query::has_view_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Query::set_has_view_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Query::clear_has_view_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Query::clear_view_name() {
  if (view_name_ != &::google::protobuf::internal::kEmptyString) {
    view_name_->clear();
  }
  clear_has_view_name();
}
inline const ::std::string& Query::view_name() const {
  return *view_name_;
}
inline void Query::set_view_name(const ::std::string& value) {
  set_has_view_name();
  if (view_name_ == &::google::protobuf::internal::kEmptyString) {
    view_name_ = new ::std::string;
  }
  view_name_->assign(value);
}
inline void Query::set_view_name(const char* value) {
  set_has_view_name();
  if (view_name_ == &::google::protobuf::internal::kEmptyString) {
    view_name_ = new ::std::string;
  }
  view_name_->assign(value);
}
inline void Query::set_view_name(const char* value, size_t size) {
  set_has_view_name();
  if (view_name_ == &::google::protobuf::internal::kEmptyString) {
    view_name_ = new ::std::string;
  }
  view_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Query::mutable_view_name() {
  set_has_view_name();
  if (view_name_ == &::google::protobuf::internal::kEmptyString) {
    view_name_ = new ::std::string;
  }
  return view_name_;
}
inline ::std::string* Query::release_view_name() {
  clear_has_view_name();
  if (view_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = view_name_;
    view_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// repeated bytes keys = 3;
inline int Query::keys_size() const {
  return keys_.size();
}
inline void Query::clear_keys() {
  keys_.Clear();
}
inline const ::std::string& Query::keys(int index) const {
  return keys_.Get(index);
}
inline ::std::string* Query::mutable_keys(int index) {
  return keys_.Mutable(index);
}
inline void Query::set_keys(int index, const ::std::string& value) {
  keys_.Mutable(index)->assign(value);
}
inline void Query::set_keys(int index, const char* value) {
  keys_.Mutable(index)->assign(value);
}
inline void Query::set_keys(int index, const void* value, size_t size) {
  keys_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Query::add_keys() {
  return keys_.Add();
}
inline void Query::add_keys(const ::std::string& value) {
  keys_.Add()->assign(value);
}
inline void Query::add_keys(const char* value) {
  keys_.Add()->assign(value);
}
inline void Query::add_keys(const void* value, size_t size) {
  keys_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
Query::keys() const {
  return keys_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
Query::mutable_keys() {
  return &keys_;
}

// optional bytes from_key = 4;
inline bool Query::has_from_key() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Query::set_has_from_key() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Query::clear_has_from_key() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Query::clear_from_key() {
  if (from_key_ != &::google::protobuf::internal::kEmptyString) {
    from_key_->clear();
  }
  clear_has_from_key();
}
inline const ::std::string& Query::from_key() const {
  return *from_key_;
}
inline void Query::set_from_key(const ::std::string& value) {
  set_has_from_key();
  if (from_key_ == &::google::protobuf::internal::kEmptyString) {
    from_key_ = new ::std::string;
  }
  from_key_->assign(value);
}
inline void Query::set_from_key(const char* value) {
  set_has_from_key();
  if (from_key_ == &::google::protobuf::internal::kEmptyString) {
    from_key_ = new ::std::string;
  }
  from_key_->assign(value);
}
inline void Query::set_from_key(const void* value, size_t size) {
  set_has_from_key();
  if (from_key_ == &::google::protobuf::internal::kEmptyString) {
    from_key_ = new ::std::string;
  }
  from_key_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Query::mutable_from_key() {
  set_has_from_key();
  if (from_key_ == &::google::protobuf::internal::kEmptyString) {
    from_key_ = new ::std::string;
  }
  return from_key_;
}
inline ::std::string* Query::release_from_key() {
  clear_has_from_key();
  if (from_key_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = from_key_;
    from_key_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional bytes to_key = 5;
inline bool Query::has_to_key() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Query::set_has_to_key() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Query::clear_has_to_key() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Query::clear_to_key() {
  if (to_key_ != &::google::protobuf::internal::kEmptyString) {
    to_key_->clear();
  }
  clear_has_to_key();
}
inline const ::std::string& Query::to_key() const {
  return *to_key_;
}
inline void Query::set_to_key(const ::std::string& value) {
  set_has_to_key();
  if (to_key_ == &::google::protobuf::internal::kEmptyString) {
    to_key_ = new ::std::string;
  }
  to_key_->assign(value);
}
inline void Query::set_to_key(const char* value) {
  set_has_to_key();
  if (to_key_ == &::google::protobuf::internal::kEmptyString) {
    to_key_ = new ::std::string;
  }
  to_key_->assign(value);
}
inline void Query::set_to_key(const void* value, size_t size) {
  set_has_to_key();
  if (to_key_ == &::google::protobuf::internal::kEmptyString) {
    to_key_ = new ::std::string;
  }
  to_key_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Query::mutable_to_key() {
  set_has_to_key();
  if (to_key_ == &::google::protobuf::internal::kEmptyString) {
    to_key_ = new ::std::string;
  }
  return to_key_;
}
inline ::std::string* Query::release_to_key() {
  clear_has_to_key();
  if (to_key_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = to_key_;
    to_key_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional uint32 limit = 6;
inline bool Query::has_limit() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Query::set_has_limit() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Query::clear_has_limit() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Query::clear_limit() {
  limit_ = 0u;
  clear_has_limit();
}
inline ::google::protobuf::uint32 Query::limit() const {
  return limit_;
}
inline void Query::set_limit(::google::protobuf::uint32 value) {
  set_has_limit();
  limit_ = value;
}

// -------------------------------------------------------------------

// Rows

// repeated bytes data = 1;
inline int Rows::data_size() const {
  return data_.size();
}
inline void Rows::clear_data() {
  data_.Clear();
}
inline const ::std::string& Rows::data(int index) const {
  return data_.Get(index);
}
inline ::std::string* Rows::mutable_data(int index) {
  return data_.Mutable(index);
}
inline void Rows::set_data(int index, const ::std::string& value) {
  data_.Mutable(index)->assign(value);
}
inline void Rows::set_data(int index, const char* value) {
  data_.Mutable(index)->assign(value);
}
inline void Rows::set_data(int index, const void* value, size_t size) {
  data_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Rows::add_data() {
  return data_.Add();
}
inline void Rows::add_data(const ::std::string& value) {
  data_.Add()->assign(value);
}
inline void Rows::add_data(const char* value) {
  data_.Add()->assign(value);
}
inline void Rows::add_data(const void* value, size_t size) {
  data_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
Rows::data() const {
  return data_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
Rows::mutable_data() {
  return &data_;
}

// -------------------------------------------------------------------

// Fetch

// optional .Db.Proto.Fetch.Type type = 1;
inline bool Fetch::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Fetch::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Fetch::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Fetch::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::Db::Proto::Fetch_Type Fetch::type() const {
  return static_cast< ::Db::Proto::Fetch_Type >(type_);
}
inline void Fetch::set_type(::Db::Proto::Fetch_Type value) {
  GOOGLE_DCHECK(::Db::Proto::Fetch_Type_IsValid(value));
  set_has_type();
  type_ = value;
}

// optional int64 id = 2;
inline bool Fetch::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Fetch::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Fetch::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Fetch::clear_id() {
  id_ = GOOGLE_LONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::int64 Fetch::id() const {
  return id_;
}
inline void Fetch::set_id(::google::protobuf::int64 value) {
  set_has_id();
  id_ = value;
}

// optional int32 storage_idx = 3;
inline bool Fetch::has_storage_idx() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Fetch::set_has_storage_idx() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Fetch::clear_has_storage_idx() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Fetch::clear_storage_idx() {
  storage_idx_ = 0;
  clear_has_storage_idx();
}
inline ::google::protobuf::int32 Fetch::storage_idx() const {
  return storage_idx_;
}
inline void Fetch::set_storage_idx(::google::protobuf::int32 value) {
  set_has_storage_idx();
  storage_idx_ = value;
}

// optional string storage_name = 4;
inline bool Fetch::has_storage_name() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Fetch::set_has_storage_name() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Fetch::clear_has_storage_name() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Fetch::clear_storage_name() {
  if (storage_name_ != &::google::protobuf::internal::kEmptyString) {
    storage_name_->clear();
  }
  clear_has_storage_name();
}
inline const ::std::string& Fetch::storage_name() const {
  return *storage_name_;
}
inline void Fetch::set_storage_name(const ::std::string& value) {
  set_has_storage_name();
  if (storage_name_ == &::google::protobuf::internal::kEmptyString) {
    storage_name_ = new ::std::string;
  }
  storage_name_->assign(value);
}
inline void Fetch::set_storage_name(const char* value) {
  set_has_storage_name();
  if (storage_name_ == &::google::protobuf::internal::kEmptyString) {
    storage_name_ = new ::std::string;
  }
  storage_name_->assign(value);
}
inline void Fetch::set_storage_name(const char* value, size_t size) {
  set_has_storage_name();
  if (storage_name_ == &::google::protobuf::internal::kEmptyString) {
    storage_name_ = new ::std::string;
  }
  storage_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Fetch::mutable_storage_name() {
  set_has_storage_name();
  if (storage_name_ == &::google::protobuf::internal::kEmptyString) {
    storage_name_ = new ::std::string;
  }
  return storage_name_;
}
inline ::std::string* Fetch::release_storage_name() {
  clear_has_storage_name();
  if (storage_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = storage_name_;
    storage_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// -------------------------------------------------------------------

// FetchData

// optional int64 id = 1;
inline bool FetchData::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FetchData::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FetchData::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FetchData::clear_id() {
  id_ = GOOGLE_LONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::int64 FetchData::id() const {
  return id_;
}
inline void FetchData::set_id(::google::protobuf::int64 value) {
  set_has_id();
  id_ = value;
}

// optional bytes buffer = 2;
inline bool FetchData::has_buffer() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void FetchData::set_has_buffer() {
  _has_bits_[0] |= 0x00000002u;
}
inline void FetchData::clear_has_buffer() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void FetchData::clear_buffer() {
  if (buffer_ != &::google::protobuf::internal::kEmptyString) {
    buffer_->clear();
  }
  clear_has_buffer();
}
inline const ::std::string& FetchData::buffer() const {
  return *buffer_;
}
inline void FetchData::set_buffer(const ::std::string& value) {
  set_has_buffer();
  if (buffer_ == &::google::protobuf::internal::kEmptyString) {
    buffer_ = new ::std::string;
  }
  buffer_->assign(value);
}
inline void FetchData::set_buffer(const char* value) {
  set_has_buffer();
  if (buffer_ == &::google::protobuf::internal::kEmptyString) {
    buffer_ = new ::std::string;
  }
  buffer_->assign(value);
}
inline void FetchData::set_buffer(const void* value, size_t size) {
  set_has_buffer();
  if (buffer_ == &::google::protobuf::internal::kEmptyString) {
    buffer_ = new ::std::string;
  }
  buffer_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* FetchData::mutable_buffer() {
  set_has_buffer();
  if (buffer_ == &::google::protobuf::internal::kEmptyString) {
    buffer_ = new ::std::string;
  }
  return buffer_;
}
inline ::std::string* FetchData::release_buffer() {
  clear_has_buffer();
  if (buffer_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = buffer_;
    buffer_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// -------------------------------------------------------------------

// WriteAhead

// optional .Db.Proto.WriteAhead.Type type = 1;
inline bool WriteAhead::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void WriteAhead::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void WriteAhead::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void WriteAhead::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::Db::Proto::WriteAhead_Type WriteAhead::type() const {
  return static_cast< ::Db::Proto::WriteAhead_Type >(type_);
}
inline void WriteAhead::set_type(::Db::Proto::WriteAhead_Type value) {
  GOOGLE_DCHECK(::Db::Proto::WriteAhead_Type_IsValid(value));
  set_has_type();
  type_ = value;
}

// optional int64 sequence = 2;
inline bool WriteAhead::has_sequence() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void WriteAhead::set_has_sequence() {
  _has_bits_[0] |= 0x00000002u;
}
inline void WriteAhead::clear_has_sequence() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void WriteAhead::clear_sequence() {
  sequence_ = GOOGLE_LONGLONG(0);
  clear_has_sequence();
}
inline ::google::protobuf::int64 WriteAhead::sequence() const {
  return sequence_;
}
inline void WriteAhead::set_sequence(::google::protobuf::int64 value) {
  set_has_sequence();
  sequence_ = value;
}

// optional int64 transact_id = 3;
inline bool WriteAhead::has_transact_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void WriteAhead::set_has_transact_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void WriteAhead::clear_has_transact_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void WriteAhead::clear_transact_id() {
  transact_id_ = GOOGLE_LONGLONG(0);
  clear_has_transact_id();
}
inline ::google::protobuf::int64 WriteAhead::transact_id() const {
  return transact_id_;
}
inline void WriteAhead::set_transact_id(::google::protobuf::int64 value) {
  set_has_transact_id();
  transact_id_ = value;
}

// optional .Db.Proto.Update update = 4;
inline bool WriteAhead::has_update() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void WriteAhead::set_has_update() {
  _has_bits_[0] |= 0x00000008u;
}
inline void WriteAhead::clear_has_update() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void WriteAhead::clear_update() {
  if (update_ != NULL) update_->::Db::Proto::Update::Clear();
  clear_has_update();
}
inline const ::Db::Proto::Update& WriteAhead::update() const {
  return update_ != NULL ? *update_ : *default_instance_->update_;
}
inline ::Db::Proto::Update* WriteAhead::mutable_update() {
  set_has_update();
  if (update_ == NULL) update_ = new ::Db::Proto::Update;
  return update_;
}
inline ::Db::Proto::Update* WriteAhead::release_update() {
  clear_has_update();
  ::Db::Proto::Update* temp = update_;
  update_ = NULL;
  return temp;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Proto
}  // namespace Db

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_2fRequest_2eproto__INCLUDED
